// <auto-generated />
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(SkiContext))]
    [Migration("20260423150620_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Resort", b =>
                {
                    b.Property<int>("ResortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResortId"));

                    b.Property<int>("AnnualSnowfall")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRuns")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerticalDrop")
                        .HasColumnType("int");

                    b.HasKey("ResortId");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            ResortId = 1,
                            AnnualSnowfall = 354,
                            Difficulty = "Advanced",
                            Name = "Vail",
                            NumberOfRuns = 195,
                            State = "Colorado",
                            VerticalDrop = 3450
                        },
                        new
                        {
                            ResortId = 2,
                            AnnualSnowfall = 355,
                            Difficulty = "Intermediate",
                            Name = "Park City Mountain",
                            NumberOfRuns = 341,
                            State = "Utah",
                            VerticalDrop = 3226
                        },
                        new
                        {
                            ResortId = 3,
                            AnnualSnowfall = 300,
                            Difficulty = "Intermediate",
                            Name = "Breckenridge",
                            NumberOfRuns = 187,
                            State = "Colorado",
                            VerticalDrop = 3398
                        },
                        new
                        {
                            ResortId = 4,
                            AnnualSnowfall = 400,
                            Difficulty = "Advanced",
                            Name = "Mammoth Mountain",
                            NumberOfRuns = 175,
                            State = "California",
                            VerticalDrop = 3100
                        },
                        new
                        {
                            ResortId = 5,
                            AnnualSnowfall = 459,
                            Difficulty = "Expert",
                            Name = "Jackson Hole",
                            NumberOfRuns = 131,
                            State = "Wyoming",
                            VerticalDrop = 4139
                        },
                        new
                        {
                            ResortId = 6,
                            AnnualSnowfall = 349,
                            Difficulty = "Intermediate",
                            Name = "Steamboat Springs",
                            NumberOfRuns = 169,
                            State = "Colorado",
                            VerticalDrop = 3668
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
